VSCode-linux/resources/app/* usr/lib/vscode

debian/code usr/bin
debian/code.js usr/lib/vscode/code.js

resources/linux/code.appdata.xml usr/share/metainfo
resources/linux/code.desktop usr/share/applications
resources/linux/code-url-handler.desktop usr/share/applications
resources/completions/bash/code usr/share/bash-completion/completions
resources/completions/zsh/_code usr/share/zsh/site-functions/_code
